### ISSUE TITLE
Does not function.

### ISSUE THREAD

**Issue by Killerscythe179** [FluxCapacitor2/PrimalFearAlert#1]
I am the #2 primal fear grinder and I downloaded this to hopefully use to be a little faster, however it does not work at all. 
I followed the exact instructions in the readme file putting the whole folder on the latest version of chattrigers available and reloaded and closed and opened my game a few times, however it does not function at all and I cannot run the commands. My other CT modules run fine, just not this one. I hope you can get back to me before the end of the event haha.

**Comment by FluxCapacitor2** [comment]
Hello, thanks for reaching out! I have a few ideas.

When extracting, make sure you've installed the folder that's *inside* the zip archive. When you download the zip, GitHub places the actual files inside a nested folder inside the zip. You want to install the folder that contains my code and not the nested folder.

For example, the `.minecraft/config/ChatTriggers/modules/PrimalFearAlert` folder should contain the `index.js` and `metadata.json` files. If there is a folder inside that folder, move those files up one level so that they're directly inside the PrimalFearAlert folder.

You should be able to see the module in the list when you type `/ct modules` ingame. Let me know if this is the case.

If the module still isn't working after that, please let me know if there are any errors in your Minecraft log files.

**Comment by Killerscythe179** [comment]
Thank you for getting back to me so quickly, I did indeed move it out of the folder when installing rather than the one github supplies and it does show up in the module list when I type /ct modules, however I cannot interact with it in any way share or form.

here's what I get

[09:41:36] [Thread-48/INFO]: [com.chattriggers.ctjs.engine.langs.js.JSLoader:entryPass:156]: Error loading module PrimalFearAlert-main
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "version" from null (file:/C:/Users/dan1s/AppData/Roaming/.minecraft/./config/ChatTriggers/modules/PrimalFearAlert-main/index.js#160)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4642)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4622)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4651)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4666)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:4680)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:2020)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.gen.file__C__Users_dan1s_AppData_Roaming__minecraft___config_ChatTriggers_modules_PrimalFearAlert_main_index_js_63._c_sendHelpMessage_8(file:/C:/Users/dan1s/AppData/Roaming/.minecraft/./config/ChatTriggers/modules/PrimalFearAlert-main/index.js:160)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.gen.file__C__Users_dan1s_AppData_Roaming__minecraft___config_ChatTriggers_modules_PrimalFearAlert_main_index_js_63.call(file:/C:/Users/dan1s/AppData/Roaming/.minecraft/./config/ChatTriggers/modules/PrimalFearAlert-main/index.js)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:83)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.gen.file__C__Users_dan1s_AppData_Roaming__minecraft___config_ChatTriggers_modules_PrimalFearAlert_main_index_js_63._c_script_0(file:/C:/Users/dan1s/AppData/Roaming/.minecraft/./config/ChatTriggers/modules/PrimalFearAlert-main/index.js:22)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.gen.file__C__Users_dan1s_AppData_Roaming__minecraft___config_ChatTriggers_modules_PrimalFearAlert_main_index_js_63.call(file:/C:/Users/dan1s/AppData/Roaming/.minecraft/./config/ChatTriggers/modules/PrimalFearAlert-main/index.js)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:342)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3951)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.gen.file__C__Users_dan1s_AppData_Roaming__minecraft___config_ChatTriggers_modules_PrimalFearAlert_main_index_js_63.call(file:/C:/Users/dan1s/AppData/Roaming/.minecraft/./config/ChatTriggers/modules/PrimalFearAlert-main/index.js)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.gen.file__C__Users_dan1s_AppData_Roaming__minecraft___config_ChatTriggers_modules_PrimalFearAlert_main_index_js_63.exec(file:/C:/Users/dan1s/AppData/Roaming/.minecraft/./config/ChatTriggers/modules/PrimalFearAlert-main/index.js)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.chattriggers.ctjs.engine.langs.js.JSLoader$CTRequire.loadCTModule(JSLoader.kt:330)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.chattriggers.ctjs.engine.langs.js.JSLoader.entryPass(JSLoader.kt:154)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.chattriggers.ctjs.engine.module.ModuleManager.entryPass(ModuleManager.kt:103)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.chattriggers.ctjs.engine.module.ModuleManager.entryPass$default(ModuleManager.kt:92)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.chattriggers.ctjs.CTJS$init$1.invoke(CTJS.kt:73)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.chattriggers.ctjs.CTJS$init$1.invoke(CTJS.kt:71)
[09:41:36] [Thread-48/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by FluxCapacitor2** [comment]
Oh okay, I know what's going on. (thanks for sharing the stack trace!) Try renaming the folder from "PrimalFearAlert-main" to just "PrimalFearAlert".

It's because I use the module name to read and write the confirmation file, and it just assumes the module name is the same as the name of the folder.

Later today, I can push a fix preventing the issue in the future.

**Comment by Killerscythe179** [comment]
Yeah, that immediately fixed it, in the meantime I wrote my own entire code to give me an alarm when the timer is up lmao
